spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/orders
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.multiTenancy=DISCRIMINATION
spring.jpa.properties.hibernate.tenant_identifier_resolver=com.jdhub.orderservice.config.TenantIdentifierResolver

spring.data.web.pageable.max-page-size=100

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
app.kafka.topics.order-events=order-events